# 端口
server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: weddingShow
  profiles:
    active: @profiles.active@

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  jackson:
    # 时间格式化
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  wechat:
    # 小程序配置
    mini-program:
      app-id: @wechat.mini-program.app-id@
      app-secret: @wechat.mini-program.app-secret@
    # 公众号配置
    public-program:
      app-id: @wechat.public-program.app-id@
      app-secret: @wechat.public-program.app-id@

admin-password: @admin.admin-password@

send-bullet-able: true

