spring:
  datasource:
    #测试环境
    url: jdbc:mysql://3.tcp.vip.cpolar.cn:12772/wedding_show?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: fjy971017@
    hikari:
      max-lifetime: 30000

share:
  link: xxxxxxxxxx
  title: xxxxxxxxxx
  desc: xxxxxxxxxxx
  image-url: xxxxxxxx

weddingshow:
  profile: /Users/liudw/Documents/wedding-show/uploadPath

  local:
    storagePath: /Users/liudw/Documents/wedding-show/uploadPath
    # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
    # https://www.tianlihotel.com/wx/storage/fetch/
    # https://www.tianlihotel.com/wx/storage/fetch/
    address: http://localhost:8888/file/fetch