spring:
  datasource:
    #测试环境
    url: jdbc:mysql://1.tcp.vip.cpolar.top:12201/wedding_show?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: fjy971017@
    hikari:
      max-lifetime: 30000

share:
  link: xxxxxxxxxx
  title: xxxxxxxxxx
  desc: xxxxxxxxxxx
  image-url: xxxxxxxx

